name: Bug Report
description: File a bug report
title: "bug: "
labels: [bug]
body:
  - type: textarea
    attributes:
      label: What's happening?
      description: Explain what you are trying to do and what happened instead. Be as precise as possible, I can't help you if I don't understand your issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduceable Code
      description: >
        Share a small reproduceable code snippet here (or the entire file if necessary).
        Most importantly, share how you use the `TurboImage` component and what props you pass to it.
        This will be automatically formatted into code, so no need for backticks.
      render: tsx
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant log output
      description: >
        Paste any relevant **native log output** (Xcode Logs/Android Studio Logcat) here.
        This will be automatically formatted into code, so no need for backticks.

        * For iOS, run the project through Xcode and copy the logs from the log window.

        * For Android, either open the project through Android Studio and paste the logs from the logcat window, or run `adb logcat` in terminal.
      render: shell
    validations:
      required: true
  - type: input
    attributes:
      label: Device
      description: >
        Which device are you seeing this Problem on?
        Mention the full name of the phone, as well as the operating system and version.
        If you have tested this on multiple devices (ex. Android and iOS) then mention all of those devices (comma separated)
      placeholder: ex. iPhone 12 (iOS 17.5)
    validations:
      required: true
  - type: input
    attributes:
      label: TurboImage Version
      description: Which version of react-native-turbo-image are you using?
      placeholder: ex. 1.14.0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Can you reproduce this issue in the TurboNetwork Example app?
      description: >
        Try to build the example app (`example/`) and see if the issue is reproduceable here.
        **Note:** If you don't try this in the example app, I most likely won't help you with your issue.
      options:
        - Yes, I can reproduce the same issue in the Example app
        - No, I cannot reproduce the issue in the Example app
      default: 0
    validations:
      required: true