name: 'Stale bot'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
permissions:
  pull-requests: write
  issues: write
jobs:
  stale:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/stale@main
        id: stale
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 15 days.'
          stale-pr-message: 'This PR is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 30 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 15 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stalled for 30 days with no activity.'
          days-before-issue-stale: 45
          days-before-pr-stale: 60
          days-before-issue-close: 15
          days-before-pr-close: 30
          exempt-issue-labels: pinned,security,no-stale
